export enum ExternalLinks {
  AnglicanCompassBCPDesign = "https://anglicanpastor.com/designed-for-mission-the-typography-of-the-acnas-new-prayer-book/",
  AnglicanCompassLectionarySpreadsheet = "https://anglicanpastor.com/heres-the-acnas-final-daily-office-lectionary-in-a-single-spreadsheet/",
  AnglicanHousePrayerBooks = "https://anglicanhousepublishers.org/prayer-books/",
  AnglicanHousePublishers = "https://anglicanhousepublishers.org/",
  BcpOfficialText = "https://bcp2019.anglicanchurch.net/index.php/downloads/",
  DailyOfficeApp = "https://dailyoffice.app/",
  DO2019 = "https://www.dailyoffice2019.com/",
  DO2019Facebook = "https://www.facebook.com/groups/dailyoffice",
  DO2019Family = "https://www.dailyoffice2019.com/family",
  DO2019GitHub = "https://github.com/blocher/dailyoffice2019",
  DO2019MailTo = "mailto:feedback@dailyoffice2019.com",
  IncarnationBcsME = "https://www.incarnationbcs.org/morning-and-evening-prayer",
  LegeremeBcp2019 = "http://bcp2019.com/",
  LiturgicalCalendar = "https://liturgical-calendar.com/",
  MissionStClare = "https://www.missionstclare.com/english/index.html",
  StAelfricCanticleGuide = "https://saint-aelfric-customary.org/2020/01/07/a-guide-to-choosing-the-supplemental-canticles/",
  StBedesBreviary = "http://www.stbedeproductions.com/breviary/",
  VeniteApp = "https://www.venite.app/",
}
